# Generated by Django 5.2 on 2026-03-02 11:14

import django.db.models.deletion
import meallogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=meallogs.models.meal_log_photo_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='meallogs.meallog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
