# Generated by Django 5.2 on 2026-03-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogs', '0002_meallogphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='uniq_tag_kind_name')],
            },
        ),
        migrations.CreateModel(
            name='MealLogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_log_tags', to='meallogs.meallog')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='meallogs.tag')),
            ],
        ),
        migrations.AddField(
            model_name='meallog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meal_logs', through='meallogs.MealLogTag', to='meallogs.tag'),
        ),
        migrations.AddConstraint(
            model_name='meallogtag',
            constraint=models.UniqueConstraint(fields=('meal_log', 'tag'), name='uniq_meallog_tag'),
        ),
    ]
