# Generated by Django 5.2 on 2026-03-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meallogs', '0003_tag_meallogtag_meallog_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLogIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'category',
                    models.SmallIntegerField(
                        choices=[
                            (0, '肉'),
                            (1, '魚'),
                            (2, '卵'),
                            (3, '野菜'),
                            (4, '豆'),
                            (5, '冷凍'),
                        ]
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'meal_log',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ingredients',
                        to='meallogs.meallog',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('meal_log', 'category'),
                        name='uniq_meallog_category',
                    )
                ],
            },
        ),
    ]
