# Generated by Django 5.2 on 2026-03-05 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('weekly_praise_enabled', models.BooleanField(default=True)),
                ('last_weekly_praise_shown_week_start', models.DateField(blank=True, null=True)),
                ('last_weekly_praise_generated_week_start', models.DateField(blank=True, null=True)),
                ('weekly_praise_payload_json', models.JSONField(blank=True, null=True)),
                ('weekly_praise_status', models.CharField(blank=True, choices=[('ok', 'ok'), ('fallback', 'fallback')], max_length=16, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
    ]
