# Generated by Django 5.2 on 2026-03-05 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jst_date', models.DateField()),
                ('used_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_daily_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_daily_usages',
                'constraints': [models.UniqueConstraint(fields=('user', 'jst_date'), name='uniq_ai_daily_usage_user_date')],
            },
        ),
    ]
